spring:
  config:
    activate:
      on-profile: ci

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

token:
  expiration_time: ${TOKEN_EXPIRATION_TIME}
  secret: ${TOKEN_SECRET}