name: Java CI with Gradle for Test Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Set environment variables
        env:
          RUN_PROFILE: ${{ secrets.RUN_PROFILE }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          TOKEN_EXPIRATION_TIME: ${{ secrets.TOKEN_EXPIRATION_TIME }}
        run: |
          echo "Environment variables set"

      - name: Verify application.yml exists
        run: cat src/main/resources/application.yml

      - name: Run tests
        run: ./gradlew test
        env:
          RUN_PROFILE: ${{ secrets.RUN_PROFILE }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          TOKEN_EXPIRATION_TIME: ${{ secrets.TOKEN_EXPIRATION_TIME }}

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582