name: Java CI with Gradle for Test Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Set environment variables
        env:
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          TOKEN_EXPIRATION_TIME: ${{ secrets.TOKEN_EXPIRATION_TIME }}
        run: |
          echo "Environment variables set"
#          echo "TOKEN_SECRET=${TOKEN_SECRET:0:3}****"
#          echo "TOKEN_EXPIRATION_TIME=${TOKEN_EXPIRATION_TIME:0:3}****"

      - name: Verify application-ci.yml exists
        run: cat src/main/resources/application-ci.yml

      - name: Run tests with CI profile
#        run: ./gradlew test -Dspring.profiles.active=ci
        run: ./gradlew test -Dspring.config.location=src/main/resources/application-ci.yml

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4